server:
  port: 9999

spring:
  application:
    name: ACCOUNTS
  datasource:
    url: jdbc:mysql://localhost:3306/accounts-db
    username: root
    password: 3gAn@130599
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always #To run the schema.sql file when starting application
  config:
    import: optional:configserver:http://localhost:8071/
  profiles:
    active: "qa"
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true #Expose shutdown API
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "accounts"
    description: "D-Corp Bank Accounts Application"
    version: "1.0.0"
