services:
  network-deploy-service:
    networks:
      - d-corp-bank

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m #limit memory location when application run

  microservice-config-server:
    extends:
      service: microservice-base-config
    depends_on:
      config-server:
        condition: service_healthy #Waiting until the config server has the readiness state UP
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      SPRING_DATASOURCE_PASSWORD: 3gAn@130599
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: 3gAn@130599