services:

  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  config-server:
    image: "phduongw/config-server:s6"
    container_name: config-server-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1
      interval: 10s #Each times to retry
      timeout: 5s #Waiting the response maximum 5s each time of retry
      retries: 10 #If there is a failure, retry for 10 times
      start_period: 10s #execute these health command only after 10s.
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "phduongw/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:9999"
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      service: microservice-config-server
      file: common-config.yml

  loans:
    image: "phduongw/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      service: microservice-config-server
      file: common-config.yml

  cards:
    image: "phduongw/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      service: microservice-config-server
      file: common-config.yml

networks:
  d-corp-bank:
    driver: "bridge"