services:
  accounts:
    image: "phduongw/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:9999"
    deploy:
      resources:
         limits:
           memory: 700m #limit memory location when application run
    networks:
      - d-corp-bank
  loans:
    image: "phduongw/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m #limit memory location when application run
    networks:
      - d-corp-bank
  cards:
    image: "phduongw/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m #limit memory location when application run
    networks:
      - d-corp-bank
networks:
  d-corp-bank:
    driver: "bridge"