server:
  port: 9999

spring:
  application:
    name: ACCOUNTS
  datasource:
    url: jdbc:mysql://localhost:3306/accounts-db
    username: root
    password: 3gAn@130599
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always #To run the schema.sql file when starting application
  config:
    import: optional:configserver:http://localhost:8071/
  profiles:
    active: "qa"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
