server:
  port: 9999

spring:
  application:
    name: ACCOUNTS
  datasource:
    url: jdbc:mysql://localhost:3306/accounts-db
    username: root
    password: 3gAn@130599
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always #To run the schema.sql file when starting application
  config:
    import: optional:configserver:http://localhost:8071/
  profiles:
    active: "qa"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true #Expose shutdown API
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "accounts"
    description: "D-Corp Bank Accounts Application"
    version: "1.0.0"
logging:
  level:
    com:
      dcorp:
        hightech:
          acounts: debug

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10 #Monitor 10 request coming, after ten request, you can take the decision whether to continue with the close or open status
        permitted-number-of-calls-in-half-open-state: 2 #allow amount of request when service in HALF OPEN status
        failure-rate-threshold: 50 #Mean 50%, when at least 50% request are failed, service will switch to OPEN state from CLOSED state
        wait-duration-in-open-state: 10000 #Mean 10 000 milliseconds = 10s, after 10s, service will switch to HALF OPEN state from OPEN state
  retry:
    configs:
      default:
        wait-duration: 500
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        max-attempts: 3
